"use client";

import Link from "next/link";
import { Camera, FileSearch, Gauge, ListChecks, ShieldCheck, type LucideIcon } from "lucide-react";

const cases = [
  {
    id: "low-light-detection-reliability",
    scenario: "Low-light detection reliability",
    setup: ["input: webcam or calibration sample", "preset: low-light route", "model: browser-side COCO-SSD", "cadence: throttled realtime inference"],
    observation: ["watch for confidence movement", "record empty inference frames", "compare observed classes before and after low-light degradation"],
    implication: "Low-light conditions can reduce observability of model behavior; production systems need frame-integrity and confidence-history monitoring.",
    evidence: ["temporal confidence trace", "operational evidence packet", "source frame replay"],
  },
  {
    id: "partial-visibility-persistence",
    scenario: "Object persistence under partial visibility",
    setup: ["input: uploaded scene or webcam", "preset: partial visibility", "degradation: occlusion + crop instability", "model: browser-side COCO-SSD"],
    observation: ["track disappearing classes", "inspect continuity breaks", "compare detections with baseline when available"],
    implication: "Object continuity should be measured rather than assumed when a system operates around occlusion or partial visibility.",
    evidence: ["tracking persistence", "drop events", "provenance: detection history only"],
  },
  {
    id: "compression-artifact-frame-integrity",
    scenario: "Frame integrity under compression artifacts",
    setup: ["input: local image or webcam", "preset: compressed feed", "degradation: noise and contrast pressure", "model: browser-side COCO-SSD"],
    observation: ["count frames with no detections", "watch class instability", "inspect mean confidence only when detections exist"],
    implication: "Compressed operational feeds can hide failure states unless telemetry exposes empty frames and confidence variance.",
    evidence: ["FRAME.INTEGRITY", "CONFIDENCE.VARIANCE", "empty frame count"],
  },
  {
    id: "motion-instability-temporal-consistency",
    scenario: "Temporal consistency under motion instability",
    setup: ["input: webcam movement or sample", "preset: motion instability", "degradation: blur + motion offset", "model: browser-side COCO-SSD"],
    observation: ["inspect adjacent-frame confidence changes", "record class continuity breaks", "compare replay timeline movement"],
    implication: "Realtime perception requires temporal instrumentation because single-frame success can hide unstable behavior across time.",
    evidence: ["TEMPORAL.CONSISTENCY", "replay timeline", "class continuity breaks"],
  },
];

const protocol = [
  "select input",
  "apply degradation preset",
  "run browser-side inference",
  "observe failure states",
  "export evidence JSON",
  "compare records without generalizing beyond the run",
];

const proofBoundary = [
  ["can show", "confidence instability, empty frames, dropped detections, and continuity breaks in this browser/model/input session"],
  ["can show", "how a selected degradation changes the emitted COCO-SSD output history"],
  ["cannot prove", "universal model failure across all detectors, datasets, environments, or deployments"],
  ["cannot prove", "overall safety of a deployed perception system without broader evaluation coverage"],
];

export default function CaseStudiesPage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#030403] text-signal-text">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_12%,rgba(71,108,81,0.10),transparent_30rem)]" />
      <section className="relative mx-auto max-w-6xl px-5 py-8 md:px-8 md:py-12">
        <Nav />
        <header className="py-12 md:py-16">
          <div className="font-mono text-[0.72rem] uppercase tracking-[0.28em] text-signal-green/80">operational case studies</div>
          <h1 className="mt-9 max-w-4xl text-4xl font-semibold leading-tight text-[#eef4ef] md:text-6xl">
            Reproducible robustness records,
            <br />
            <span className="text-[#aeb8b1]">not synthetic benchmark stories.</span>
          </h1>
          <p className="mt-8 max-w-3xl text-sm leading-relaxed text-signal-muted">
            These notes define repeatable perception robustness protocols. Evidence is generated by running the SIGNALWATCH perception lab and reading the model-output history, not by prefilled analytics.
          </p>
        </header>

        <section className="grid gap-4 lg:grid-cols-2">
          {cases.map((item) => (
            <CaseCard key={item.id} {...item} />
          ))}
        </section>

        <section className="mt-5 grid gap-5 lg:grid-cols-[.9fr_1.1fr]">
          <div className="console-panel p-5">
            <div className="flex items-center gap-2 border-b border-[#101b15] pb-3 font-mono text-[0.68rem] uppercase text-signal-green/80">
              <ListChecks className="h-3.5 w-3.5" />
              evidence protocol
            </div>
            <div className="mt-5 space-y-2">
              {protocol.map((step, index) => (
                <div key={step} className="grid grid-cols-[2.2rem_1fr] gap-3 border-l border-[#18271d] bg-[#050806]/62 px-3 py-2 font-mono text-[0.62rem] uppercase text-signal-muted">
                  <span className="text-signal-green/70">{String(index + 1).padStart(2, "0")}</span>
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="console-panel p-5">
            <div className="flex items-center gap-2 border-b border-[#101b15] pb-3 font-mono text-[0.68rem] uppercase text-signal-green/80">
              <ShieldCheck className="h-3.5 w-3.5" />
              proof boundary
            </div>
            <div className="mt-5 grid gap-3 md:grid-cols-2">
              {proofBoundary.map(([label, text]) => (
                <div key={`${label}-${text}`} className="border border-[#101b15] bg-[#050806]/62 p-3">
                  <div className="font-mono text-[0.58rem] uppercase text-signal-green/70">{label}</div>
                  <p className="mt-2 text-sm leading-relaxed text-signal-muted">{text}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <section className="mt-5 console-panel p-5">
          <div className="flex items-center gap-2 border-b border-[#101b15] pb-3 font-mono text-[0.68rem] uppercase text-signal-green/80">
            <ShieldCheck className="h-3.5 w-3.5" />
            reproducibility boundary
          </div>
          <p className="mt-5 max-w-3xl text-sm leading-relaxed text-signal-muted">
            Case-study evidence should be captured from the operational evidence packet: frame count, empty frames, confidence history, detection drop events, class continuity breaks, and exported JSON records. If the model emits no detections, the record should state that plainly.
          </p>
        </section>
      </section>
    </main>
  );
}

function Nav() {
  return (
    <nav className="flex items-center justify-between border-b border-[#101b15] pb-4 font-mono text-[0.68rem] uppercase text-signal-dim">
      <Link href="/" className="text-signal-green/80 transition hover:text-signal-green">JGSOPS</Link>
      <div className="flex flex-wrap items-center justify-end gap-4">
        <Link href="/console" className="transition hover:text-signal-text">console</Link>
        <Link href="/evaluations" className="transition hover:text-signal-text">evaluations</Link>
        <Link href="/labs/perception" className="transition hover:text-signal-text">perception</Link>
        <Link href="/case-studies" className="text-signal-green/80 transition hover:text-signal-green">case studies</Link>
      </div>
    </nav>
  );
}

function CaseCard({
  scenario,
  setup,
  observation,
  implication,
  evidence,
}: {
  scenario: string;
  setup: string[];
  observation: string[];
  implication: string;
  evidence: string[];
}) {
  return (
    <article className="border border-[#101b15] bg-[#050806]/70 p-5 transition hover:border-[#24392c]">
      <div className="flex items-center gap-2 font-mono text-[0.68rem] uppercase text-signal-green/80">
        <FileSearch className="h-3.5 w-3.5" />
        {scenario}
      </div>
      <div className="mt-5 grid gap-4 md:grid-cols-2">
        <Block icon={Camera} title="setup" items={setup} />
        <Block icon={Gauge} title="observation" items={observation} />
      </div>
      <div className="mt-4 border-l border-[#24392c] bg-[#050806]/62 px-3 py-2">
        <div className="font-mono text-[0.6rem] uppercase text-signal-green/70">operational implication</div>
        <p className="mt-1 text-sm leading-relaxed text-signal-muted">{implication}</p>
      </div>
      <div className="mt-4 flex flex-wrap gap-1.5 font-mono text-[0.58rem] uppercase text-signal-dim">
        {evidence.map((item) => (
          <span key={item} className="border border-[#101b15] bg-[#07100b]/70 px-1.5 py-1">{item}</span>
        ))}
      </div>
      <Link href="/labs/perception" className="mt-5 inline-flex border border-[#203528] bg-[#07100b] px-3 py-2 font-mono text-[0.62rem] uppercase text-signal-green/80 transition hover:border-[#3e654c]">
        run protocol
      </Link>
    </article>
  );
}

function Block({ icon: Icon, title, items }: { icon: LucideIcon; title: string; items: string[] }) {
  return (
    <div>
      <div className="flex items-center gap-2 font-mono text-[0.6rem] uppercase text-signal-green/70">
        <Icon className="h-3 w-3" />
        {title}
      </div>
      <div className="mt-2 space-y-1 text-sm leading-relaxed text-signal-muted">
        {items.map((item) => <div key={item}>{item}</div>)}
      </div>
    </div>
  );
}
